### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by egodigitus** [OpenManufacturingPlatform/iot_connectivity_public#5]
Can anybody contribute? 
Even if you're not working within one of the member companies of the working group?

**Comment by sbuckel** [comment]
Hi egodigitus,

We welcome external contributors. You have the possibility to open a GitHub issue or to create a pull request against a certain content. The issue will then be put on the agenda of our next meeting and we will get back to you.

Nonetheless, collaboration in our regular meetings and thus the possibility to influence the selection, guidelines and prioritization of our topics is only possible for members of the OMP.

Sebastian 
(Chair of the working group IoT Connectivity)
